# Dataframes in Padas
A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [1]:
import numpy as np
import pandas as pd

## Creating a Dataframe

In [2]:
data = {
    "Name"   : ["Mohit","Rohit","Sohit","Mayank"],
    "Age"    : [19, 24, 30, 20],
    "City"   : ["Delhi", "Jaipur", "Ranchi", "Gurgaon"],
    "Salary" : [20000,22000,250000,430000]
}
df_alpha = pd.DataFrame(data)
df_alpha

     Name  Age     City  Salary
0   Mohit   19    Delhi   20000
1   Rohit   24   Jaipur   22000
2   Sohit   30   Ranchi  250000
3  Mayank   20  Gurgaon  430000

In [3]:
data_list = [["Mohit","Rohit","Sohit","Mayank"],[19, 24, 30, 20],["Delhi", "Jaipur", "Ranchi", "Gurgaon"],[20000,22000,250000,430000]]
pd.DataFrame(data_list)

       0       1       2        3
0  Mohit   Rohit   Sohit   Mayank
1     19      24      30       20
2  Delhi  Jaipur  Ranchi  Gurgaon
3  20000   22000  250000   430000

In [4]:
data_list = [
    ['Mohit', 19, 'Delhi', 20000],
    ['Rohit', 24, 'Jaipur', 22000],
    ['Sohit', 30, 'Ranchi', 250000],
    ['Mayank', 20, 'Gurgaon', 430000]
]
pd.DataFrame(data_list)

        0   1        2       3
0   Mohit  19    Delhi   20000
1   Rohit  24   Jaipur   22000
2   Sohit  30   Ranchi  250000
3  Mayank  20  Gurgaon  430000

In [5]:
columns=['Name','Age','City','Salary']
df = pd.DataFrame(data_list,columns=columns)
df

     Name  Age     City  Salary
0   Mohit   19    Delhi   20000
1   Rohit   24   Jaipur   22000
2   Sohit   30   Ranchi  250000
3  Mayank   20  Gurgaon  430000

## Selection and Indexing of Columns

In [6]:
df['Name']

0     Mohit
1     Rohit
2     Sohit
3    Mayank
Name: Name, dtype: object

In [7]:
df[['Name','City']]

     Name     City
0   Mohit    Delhi
1   Rohit   Jaipur
2   Sohit   Ranchi
3  Mayank  Gurgaon

## Creating a new Column

In [8]:
df["Designation"] = ['Doctor','Engineer','Teacher','Influencer']
df

     Name  Age     City  Salary Designation
0   Mohit   19    Delhi   20000      Doctor
1   Rohit   24   Jaipur   22000    Engineer
2   Sohit   30   Ranchi  250000     Teacher
3  Mayank   20  Gurgaon  430000  Influencer

## Removing Columns

In [9]:
df.drop('Age',axis=1)
df # We can see No change

     Name  Age     City  Salary Designation
0   Mohit   19    Delhi   20000      Doctor
1   Rohit   24   Jaipur   22000    Engineer
2   Sohit   30   Ranchi  250000     Teacher
3  Mayank   20  Gurgaon  430000  Influencer

In [10]:
df.drop('Age',axis=1,inplace=True)
df

     Name     City  Salary Designation
0   Mohit    Delhi   20000      Doctor
1   Rohit   Jaipur   22000    Engineer
2   Sohit   Ranchi  250000     Teacher
3  Mayank  Gurgaon  430000  Influencer

In [11]:
df.drop(2,inplace=True)
df

     Name     City  Salary Designation
0   Mohit    Delhi   20000      Doctor
1   Rohit   Jaipur   22000    Engineer
3  Mayank  Gurgaon  430000  Influencer

## Selecting Rows

In [12]:
df

     Name     City  Salary Designation
0   Mohit    Delhi   20000      Doctor
1   Rohit   Jaipur   22000    Engineer
3  Mayank  Gurgaon  430000  Influencer

In [13]:
df.loc[0]

Name            Mohit
City            Delhi
Salary          20000
Designation    Doctor
Name: 0, dtype: object

In [14]:
df.loc[[0,1]]

    Name    City  Salary Designation
0  Mohit   Delhi   20000      Doctor
1  Rohit  Jaipur   22000    Engineer

In [15]:
df_alpha.iloc[2]

Name       Sohit
Age           30
City      Ranchi
Salary    250000
Name: 2, dtype: object